version: "3.9"

services:
  weather-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:80" # Host:Container port mapping
    environment:
      - NODE_ENV=production
